package com.myspace.kafkaread2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KafkaContext implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public KafkaContext() {
    }




}